### ISSUE TITLE
bot.commands+regex+triggers should be rebuilt.

### ISSUE THREAD

**Issue by itslukej** [ezzybot/ezzybot#19]
I think it would be better if he did options such as commandname etc as attributes to the commands function, this can all be set in ezzybot.util.hook.command etc

**Comment by Bowserinator** [comment]
😆

**Comment by itslukej** [comment]
Pull request made, does bring a lot of issues. https://github.com/ezzybot/ezzybot/pull/20

**Comment by Bowserinator** [comment]
[Insert reply here]

**Comment by BWBellairs** [comment]
Placeholder text
