### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by IndigoTiger** [ezzybot/ezzybot#23]
ezzybot currently lacks support for Python 3, this isn't a major issue since Python 2 is the default in most cases but supporting Python 3 would be nice.

**Comment by BWBellairs** [comment]
That would be easy to do but it would take to long to complete... Maybe we can use the python module (2.7) to convert each file to python3?

**Comment by itslukej** [comment]
ThingDB and its requirements support python3, not sure about PySocks (for proxying)

**Comment by BWBellairs** [comment]
hmm
We should disabled proxy for python3 then until we have a suitable alternative

**Comment by IndigoTiger** [comment]
Just tested PySocks + Python 3, It worked fine for me
