### ISSUE TITLE
Add an option to delay reconnect after KILL or GLINE

### ISSUE THREAD

**Issue by io4** [ezzybot/ezzybot#39]
Bot should add delay, setable in config, after being disconnected from the network because of KILL or G-Line.

KILL will send KILL command, and G-Line, a notice saying You was banned from <network> (<reason>) or ERROR starting with G-Line:

**Comment by itslukej** [comment]
https://github.com/dev-zz/ezzybot/commit/886aff0c0d47e18214da803b0b44d11693c14301
