### ISSUE TITLE
Problems with bot reconnecting

### ISSUE THREAD

**Issue by itslukej** [ezzybot/ezzybot#45]
Issues:
 - The Bot may have the connection open and cause errors
 - The bot may have a closed connection, and ping_timer will continue sending querys, causing errors
 - The bot may attempt a reconnect but fail (connection problems)
 - Plugins that take a while to run may disrupt the time PONG is recieved from the server, causing the bot to think it is lagging... (and continue to fail a reconnection)

Best to remake the whole stay connected thing all together.

**Comment by BWBellairs** [comment]
The bot disconnecting on an error?

**Comment by itslukej** [comment]
This is being worked on for Ezzybot bot.py build 2

**Comment by itslukej** [comment]
Most of these were fixed today
https://github.com/dev-zz/ezzybot/commit/886aff0c0d47e18214da803b0b44d11693c14301
